import { KeyRound, MapPin, UserPlus } from "lucide-react";
import { createClientAccount, createClientUser, createShippingAddress } from "@/lib/actions/admin";
import { createClient } from "@/lib/supabase/server";

export default async function ClientsPage() {
  const supabase = await createClient();
  const [{ data: clients }, { data: direcciones }] = await Promise.all([
    supabase.from("clients").select("id, razon_social, rfc, contacto_email, odoo_partner_id, activo").order("razon_social"),
    supabase.from("shipping_addresses").select("id, client_id, etiqueta, calle, ciudad, estado, cp, es_default"),
  ]);
  return <><nav className="nav"><span className="nav-brand">Telas Xalostoc / Admin</span><a className="nav-link" href="/admin/productos">Productos</a><a className="nav-link active" href="/admin/clientes">Clientes</a><a className="nav-link" href="/admin/bandeja">Bandeja</a></nav><main className="wrap main"><div className="dashboard-head"><div><span className="kicker">Administración / Cuentas</span><h1>Clientes</h1><p className="muted">Cuentas recurrentes y mapeos estáticos de Odoo.</p></div></div><div className="grid">
    <section className="card blueprint span-4"><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/><span className="kicker">01 · Nueva cuenta</span><h2 style={{ fontSize:27 }}>Agregar cliente</h2><form action={createClientAccount} className="login-form"><div className="field"><label htmlFor="razon_social">Razón social</label><input className="input" id="razon_social" name="razon_social" placeholder="Confecciones del Centro, S.A." required /></div><div className="field"><label htmlFor="rfc">RFC</label><input className="input" id="rfc" name="rfc" placeholder="CCE010101ABC" /></div><div className="field"><label htmlFor="contacto_email">Correo de contacto</label><input className="input" id="contacto_email" name="contacto_email" type="email" placeholder="compras@empresa.com" required /></div><div className="field"><label htmlFor="odoo_partner_id">ID partner Odoo <span className="muted">(opcional)</span></label><input className="input" id="odoo_partner_id" name="odoo_partner_id" type="number" min="1" placeholder="Pendiente" /></div><button className="btn btn-primary blueprint" type="submit"><UserPlus size={15} strokeWidth={1.5}/> Guardar cliente</button></form></section>
    <section className="card blueprint span-4"><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/><span className="kicker">02 · Acceso portal</span><h2 style={{ fontSize:27 }}>Crear usuario</h2><form action={createClientUser} className="login-form"><div className="field"><label htmlFor="client_id">Cliente</label><select className="input" id="client_id" name="client_id" required defaultValue=""><option value="" disabled>Selecciona una cuenta</option>{(clients ?? []).map((client) => <option key={client.id} value={client.id}>{client.razon_social}</option>)}</select></div><div className="field"><label htmlFor="user_email">Correo de acceso</label><input className="input" id="user_email" name="user_email" type="email" placeholder="compras@empresa.com" required /></div><div className="field"><label htmlFor="user_password">Contraseña temporal</label><input className="input" id="user_password" name="user_password" type="password" minLength={8} placeholder="Mínimo 8 caracteres" required /></div><button className="btn btn-primary blueprint" type="submit"><KeyRound size={15} strokeWidth={1.5}/> Crear acceso</button></form></section>
    <section className="card blueprint span-4"><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/><span className="kicker">03 · Directorio</span><h2 style={{ fontSize:27 }}>Clientes registrados</h2><div className="table-wrap"><table className="table"><thead><tr><th>Razón social</th><th>RFC</th><th>Correo</th><th>Odoo</th><th>Estado</th></tr></thead><tbody>{(clients ?? []).map((client) => <tr key={client.id}><td>{client.razon_social}</td><td className="muted">{client.rfc || "-"}</td><td>{client.contacto_email}</td><td className="muted">{client.odoo_partner_id ?? "-"}</td><td><span className="status">{client.activo ? "Activo" : "Inactivo"}</span></td></tr>)}</tbody></table>{!clients?.length && <p className="muted" style={{ padding:20 }}>No hay clientes registrados.</p>}</div></section>
    <section className="card blueprint span-4"><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/><span className="kicker">04 · Entregas</span><h2 style={{ fontSize:27 }}>Dirección de entrega</h2><p className="muted" style={{ fontSize:13 }}>El cliente la elige al confirmar el carrito. Sin direcciones cargadas, ese selector no aparece.</p><form action={createShippingAddress} className="login-form"><div className="field"><label htmlFor="addr_client_id">Cliente</label><select className="input" id="addr_client_id" name="addr_client_id" required defaultValue=""><option value="" disabled>Selecciona una cuenta</option>{(clients ?? []).map((client) => <option key={client.id} value={client.id}>{client.razon_social}</option>)}</select></div><div className="field"><label htmlFor="etiqueta">Etiqueta</label><input className="input" id="etiqueta" name="etiqueta" placeholder="Matriz, Sucursal Norte..."/></div><div className="field"><label htmlFor="calle">Calle y número</label><input className="input" id="calle" name="calle" required/></div><div className="field"><label htmlFor="ciudad">Ciudad</label><input className="input" id="ciudad" name="ciudad"/></div><div className="field"><label htmlFor="estado_dir">Estado</label><input className="input" id="estado_dir" name="estado_dir"/></div><div className="field"><label htmlFor="cp">Código postal</label><input className="input" id="cp" name="cp" inputMode="numeric"/></div><label style={{ display:"flex", alignItems:"center", gap:8, fontSize:13 }}><input type="checkbox" name="es_default"/> Usar como predeterminada</label><button className="btn btn-secondary" type="submit"><MapPin size={15} strokeWidth={1.5}/> Guardar dirección</button></form><hr className="hr"/><div className="table-wrap"><table className="table"><thead><tr><th>Cliente</th><th>Dirección</th></tr></thead><tbody>{(direcciones ?? []).map((d) => <tr key={d.id}><td className="muted">{(clients ?? []).find((c) => c.id === d.client_id)?.razon_social ?? "-"}</td><td>{[d.etiqueta, d.calle, d.ciudad, d.estado, d.cp].filter(Boolean).join(" · ")}{d.es_default && <span className="status" style={{ marginLeft:6 }}>default</span>}</td></tr>)}</tbody></table>{!direcciones?.length && <p className="muted" style={{ padding:16 }}>Aún no hay direcciones cargadas.</p>}</div></section>
  </div></main></>;
}
