import { RefreshCw, ArrowLeftRight } from "lucide-react";
import { AdminNav } from "@/components/app-nav";
import { retrySync, runCatalogSync } from "@/lib/actions/sync";
import { MAX_INTENTOS_SYNC } from "@/lib/odoo/limits";
import { createClient } from "@/lib/supabase/server";
import { etiquetaStaff } from "@/lib/order-status";

export default async function SyncPage() {
  const supabase = await createClient();
  const { data: ultimaSync } = await supabase.from("sync_log").select("exito, error_msg, odoo_response, created_at").is("order_id", null).order("created_at", { ascending: false }).limit(1).maybeSingle();
  const resumen = (ultimaSync?.odoo_response ?? null) as { productos?: { nuevosEnPortal: number; actualizados: number; nuevosEnOdoo: number }; clientes?: { nuevosEnPortal: number; nuevosEnOdoo: number }; precios?: { asignados: number } } | null;
  const { data: orders } = await supabase.from("orders").select("id, folio, status, subtotal, updated_at, sync_log(intento, exito, error_msg, created_at)").in("status", ["sync_error", "sincronizado"]).order("updated_at", { ascending: false });
  return <><AdminNav activo="/admin/sync"/><main className="wrap main"><span className="kicker">Admin / Integración</span><h1>Sync Odoo</h1><p className="muted">Pedidos aprobados, errores y reintentos. El modo actual es <strong style={{ color:"var(--text)" }}>{process.env.ODOO_SYNC_ENABLED === "true" ? "API Odoo" : "fallback"}</strong>.</p><section className="card blueprint" style={{ marginTop:36 }}><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/><span className="kicker">01 · Catálogo y cuentas</span><h2 style={{ fontSize:27 }}>Sincronizar con Odoo</h2><p className="muted" style={{ fontSize:13, maxWidth:620 }}>Trae productos y clientes nuevos desde Odoo, empuja hacia Odoo los que se dieron de alta aquí y actualiza los precios por cliente desde las pricelists. No toca el estado <strong style={{ color:"var(--text)" }}>activo</strong> de los productos: eso lo controla el portal.</p>{ultimaSync && <p className="muted" style={{ fontSize:13 }}>Última corrida: {new Date(ultimaSync.created_at).toLocaleString("es-MX")} · <span className="status">{ultimaSync.exito ? "sin errores" : "con errores"}</span>{resumen && <> · productos {resumen.productos?.nuevosEnPortal ?? 0} nuevos / {resumen.productos?.actualizados ?? 0} actualizados / {resumen.productos?.nuevosEnOdoo ?? 0} creados en Odoo · clientes {resumen.clientes?.nuevosEnPortal ?? 0} nuevos / {resumen.clientes?.nuevosEnOdoo ?? 0} creados en Odoo · precios {resumen.precios?.asignados ?? 0}</>}</p>}{ultimaSync?.error_msg && <p className="muted" style={{ fontSize:12, color:"var(--accent-700)" }}>{ultimaSync.error_msg}</p>}<form action={runCatalogSync}><button className="btn btn-primary blueprint" type="submit"><ArrowLeftRight size={15} strokeWidth={1.5}/> Sincronizar ahora</button></form></section>

    <section className="card blueprint" style={{ marginTop:24 }}><span className="kicker">02 · Pedidos</span><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/><table className="table"><thead><tr><th>Folio</th><th>Estado</th><th>Última actualización</th><th>Intentos</th><th>Último error</th><th/></tr></thead><tbody>{(orders ?? []).map((order) => { const logs = Array.isArray(order.sync_log) ? order.sync_log : []; const latest = logs[logs.length - 1]; const fallos = logs.filter((l) => !l.exito).length; const agotado = fallos >= MAX_INTENTOS_SYNC; return <tr key={order.id}><td data-label="Folio">{order.folio}</td><td data-label="Estado"><span className="status">{etiquetaStaff(order.status)}</span></td><td data-label="Última actualización">{new Date(order.updated_at).toLocaleString("es-MX")}</td><td data-label="Intentos" className="muted">{order.status === "sync_error" ? <>{fallos}/{MAX_INTENTOS_SYNC}{agotado && <span className="status" style={{ marginLeft:6 }}>agotado</span>}</> : "-"}</td><td data-label="Último error" className="muted" style={{ maxWidth:280 }}>{latest?.error_msg ?? "-"}</td><td>{order.status === "sync_error" && <form action={retrySync}><input type="hidden" name="order_id" value={order.id}/><button className="btn btn-secondary" type="submit"><RefreshCw size={13} strokeWidth={1.5}/> Reintentar</button></form>}</td></tr>; })}</tbody></table>{!orders?.length && <p className="muted" style={{ padding:20 }}>No hay pedidos sincronizados o con error.</p>}
      <p className="muted" style={{ fontSize:12, marginTop:14 }}>Tras {MAX_INTENTOS_SYNC} intentos fallidos el reintento automático se detiene y se avisa al validador por correo. El botón «Reintentar» sigue funcionando: ignora el tope a propósito.</p>
    </section></main></>;
}
