import { RefreshCw } from "lucide-react";
import { retrySync } from "@/lib/actions/sync";
import { createClient } from "@/lib/supabase/server";

export default async function SyncPage() {
  const supabase = await createClient();
  const { data: orders } = await supabase.from("orders").select("id, folio, status, subtotal, updated_at, sync_log(intento, exito, error_msg, created_at)").in("status", ["sync_error", "sincronizado"]).order("updated_at", { ascending: false });
  return <><nav className="nav"><span className="nav-brand">Telas Xalostoc / Operaciones</span><a className="nav-link" href="/admin/bandeja">Bandeja</a><a className="nav-link active" href="/admin/sync">Sync Odoo</a></nav><main className="wrap main"><span className="kicker">Admin / Integración</span><h1>Sync Odoo</h1><p className="muted">Pedidos aprobados, errores y reintentos. El modo actual es <strong style={{ color:"var(--text)" }}>{process.env.ODOO_SYNC_ENABLED === "true" ? "API Odoo" : "fallback"}</strong>.</p><section className="card blueprint" style={{ marginTop:36 }}><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/><table className="table"><thead><tr><th>Folio</th><th>Estado</th><th>Última actualización</th><th>Último error</th><th/></tr></thead><tbody>{(orders ?? []).map((order) => { const logs = Array.isArray(order.sync_log) ? order.sync_log : []; const latest = logs[logs.length - 1]; return <tr key={order.id}><td>{order.folio}</td><td><span className="status">{order.status}</span></td><td>{new Date(order.updated_at).toLocaleString("es-MX")}</td><td className="muted">{latest?.error_msg ?? "-"}</td><td>{order.status === "sync_error" && <form action={retrySync}><input type="hidden" name="order_id" value={order.id}/><button className="btn btn-secondary" type="submit"><RefreshCw size={13} strokeWidth={1.5}/> Reintentar</button></form>}</td></tr>; })}</tbody></table>{!orders?.length && <p className="muted" style={{ padding:20 }}>No hay pedidos sincronizados o con error.</p>}</section></main></>;
}
